# Override for webrtc-ros-bridge: front camera topic and headless (no Pangolin GUI).
# Used when launching ORB-SLAM3 mono from the slam service.
ORB_SLAM3_MONO_ROS2:
  ros__parameters:
    robot_base_frame: base_footprint
    global_frame: map
    odom_frame: odom
    image_topic_name: /robot/video/front
    robot_x: 0.0
    robot_y: 0.0
    robot_z: 0.0
    robot_qx: 0.0
    robot_qy: 0.0
    robot_qz: 0.0
    robot_qw: 1.0
    visualization: false
    odometry_mode: false
    publish_tf: true
    map_data_publish_frequency: 1000
    do_loop_closing: true
